### PR TITLE
Fix creating unusable ZIP files on Windows

### LINKED ISSUE #76: Subdirs in zip have wrong file attributes
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gulp-zip/issues/76)

Similar to this topic here - https://github.com/sindresorhus/gulp-zip/issues/62

This is still happening to me but only on SUB-directories, I am using v3.2.0 - however what I do differently is my main system is Windows. So I run the gulp script on my Windows system and when I send my zip to others who open it on Ubuntu they see this:

The first level directories are fine, but directories inside those directories are like this.

First level directories are fine:

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Submitted pull Requests
- [#117  Fix creating unusable zip files on Windows (missing executable bit on directories)](https://issuehunt.io/r/sindresorhus/gulp-zip/pull/117)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gulp-zip/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### LINKED ISSUE #106: Can't open zip on Mac OS
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gulp-zip/issues/106)

When the package is created on Windows, I cannot open it using Mac OS:
screen shot 2018-09-27 at 09 56 38

Everything works well when the package is created on Mac OS or Linux (tested on Ubuntu 18.04).
What's important, I can extract zip file using "The Unarchiver", but not using default Archive Utility. It's important to make it work with Archive Utility because I can't tell all my clients to use different software. Any thoughts?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Submitted pull Requests
- [#117  Fix creating unusable zip files on Windows (missing executable bit on directories)](https://issuehunt.io/r/sindresorhus/gulp-zip/pull/117)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gulp-zip/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### LINKED ISSUE #112: gulp-zip change folder permission,  from 755 to 666
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gulp-zip/issues/112)

Hi today my team member happened to meet this issue.

Normal:
image

But after gulp-zip: 
image

and **this issue only occurs on Windows**, my machine is Mac, never has this problem.

Following is my code:
```
var gulp = require('gulp');
var gulpZip = require('gulp-zip');
var gulpIf = require('gulp-if');
var gulpChmod = require('gulp-chmod');
var gulpTap = require('gulp-tap');
var moment = require('moment');
var colors = require('colors[表情]fe');
// 打包
function isDirectory(file) {
    console.log(file, file.isDirectory())
    return file.isDirectory()
}
gulp.task('zip', function() {
    var timestamp = moment().format('YYYY-MM-DD_HHMMSS');
    var fileName = 'static-' + timestamp + '.zip';
    console.log(colors.green('*******COPY THIS PATH TO DEPLOY: ' + 'qly_industry/' + fileName))
    return gulp.src('./dist/**')
        // .pipe(gulpIf(isDirectory, gulpChmod(0o777)))
        .pipe(gulpTap(function(file) {
            if (file.isDirectory()) {
                file.stat.mode = parseInt(40755, 8)
            }
        }))
        .pipe(gulpZip(fileName))
        .pipe(gulp.dest('./dist'));
});
```

After I tried `gulp-chmod` and `gulp-tap` as other issues you mentioned to fix likely problem,  still can't fix this issue!

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $30.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($30.00)

### Submitted pull Requests
- [#117  Fix creating unusable zip files on Windows (missing executable bit on directories)](https://issuehunt.io/r/sindresorhus/gulp-zip/pull/117)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gulp-zip/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by Jimbly**
Fixes #112
Fixes #106 
Fixes #76

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#112: gulp-zip change folder permission,  from 755 to 666](https://issuehunt.io/repos/15377028/issues/112)
- [#106: Can't open zip on Mac OS](https://issuehunt.io/repos/15377028/issues/106)
- [#76: Subdirs in zip have wrong file attributes](https://issuehunt.io/repos/15377028/issues/76)
---
</details>

### CODE REVIEW

**Comment by Jimbly** [comment]
From what I understand, the root of this issue is that mode bits on directories in zip files are platform-specific, usually .zip files contain no directory information, only files, or all directories have a mode of 0, which leaves it up to the platform to decide what to do.  Just passing a mode of 0 along for the directory entries would probably also be a perfectly valid fix.

File: index.js [hunk 1]
```diff
@@ -35,7 +35,9 @@ module.exports = (filename, options) => {
 		if (file.isNull() && file.stat && file.stat.isDirectory && file.stat.isDirectory()) {
 			zip.addEmptyDirectory(pathname, {
 				mtime: options.modifiedTime || file.stat.mtime || new Date(),
-				mode: file.stat.mode
+				// Set executable bit on directories if any other bits are set for that user/group/all
+				// Fixes creating unusable zip files on platforms that do not use an executable bit
+				mode: file.stat.mode | (((file.stat.mode >> 1) | (file.stat.mode >> 2)) & 0o111)
```
Comment (sindresorhus) [inline index.js:40]: Shouldn't this be fixed in https://github.com/gulpjs/vinyl-fs ? This plugin just passes the `.mode` it gets from there.

Comment (sindresorhus) [reply index.js:40]: Hmm, or actually, this seems like an issue in https://github.com/thejoshwolfe/yazl ? Since it should correctly handle a normal mode and do the right thing depending on the platform.

Comment (Jimbly) [reply index.js:40]: Perhaps?  YAZL is already exposing `addEmptyDirectory` as something special - empty directories in zip files are only cross-platform if you use a default mode of 0, as far as I understand it, so maybe should just always passing `0` here would be fine?

Comment (Jimbly) [reply index.js:40]: I think it would be very weird for YAZL to do anything with the 'mode' bits passed to it other than store it directly in the zip file (for people using zips on a single environment that's sometimes important).  Presumably most people are using `gulp-zip` as a part of build and distribution pipelines, where the output is expected to be cross-platform / just work.

Comment (sindresorhus) [reply index.js:40]: I just feel that YAZL should not allow creating ZIPs that end up being invalid on certain platforms. It would be better if YAZL either threw and error or did the right thing. Don't you agree?

As for fixing this here, I'm fine with just passing `0`.

---

> where the output is expected to be cross-platform / just work.

I cannot imagine any real scenario where you wouldn't want it to be cross-platform. You never know where the ZIP will eventually be used.

Comment (Jimbly) [reply index.js:40]: The exception is when you're doing system maintenance kind of stuff - if I make a zip of my user directory, I would, perhaps, expect it to save the platform-specific mode bits and restore them when I unzip them.  But, since it doesn't include other platform-specific stuff like owner and group or security ACLs, it'd be a horrible choice for anything maintenance related, so maybe you're right and it just shouldn't be that way, but that seems to be the way zip is.  If you make a zip on Windows with the built-in PowerShell zip function, it *also* makes incompatible zip files in the same way :(.  This really seems like a bug in the unzipping side, but that's quite far out of our control =).

Upon consideration, I agree my earlier arguments about cross-platform should apply to YAZL, even if I also think that would be weird - I'll send the same PR setting the executable bits inside of `addEmptyDirectory()` to YAZL and see how that maintainer feels =)

Comment (Jimbly) [reply index.js:40]: Sent a [PR](https://github.com/thejoshwolfe/yazl/pull/59) over to YAZL, but it's been silent so far.  Sounds like YAZL is [only semi-maintained](https://github.com/thejoshwolfe/yazl/issues/58), so might take some time before it gets resolved or rejected.

**Comment by Jimbly** [comment]
Well, it's been a month and a half, and zero activity from the maintainer of YAZL, so I don't expect the PR over there will be merged any time soon, if ever...  Want to fix this here, or should we make a fork of YAZL with bugfixes and depend on that instead?

**Comment by sindresorhus** [comment]
I’m ok with fixing it here. Can you add a code comment with a link to the YAZL issue? I’m case it ever gets fixed and we can remove the workaround.

**Comment by Jimbly** [comment]
Sure, can do.  Do you prefer the change as-written (adding the executable bit) or just passing `mode: 0` (or no mode at all, if that works)?  Passing no mode would probably be cleaner and would always make platform-independent zip files, but if someone was using this to zip directories with a mode of 0700 or something it would now discard that information (but I can't imagine anyone using gulp-zip in a context where that would matter).

**Comment by sindresorhus** [comment]
I would prefer passing `mode: 0` or no mode at all.

**Comment by Jimbly** [comment]
Okay, have committed the simpler fix.  Two notes:
* When I gulp-zip something and then unzip on Linux, now all of the files are 0777 but directories are 0775 (was previously 0666 if gulp-zipped on Windows, which was obviously wrong, and presumably 0777 if gulp-zipped on Linux).  I think this is probably fine.
* yauzl returns the full mode bits, and YAZL's default is `S_IFDIR | 0775` so the test gets that now that we're not explicitly specifying a mode, so I'm doing a `& 0777` in the tests. This test as-written would fail after if my PR to YAZL was accepted anyway (which makes it consistent about passing S_IFDIR).
